### ISSUE TITLE
Blackmagic Intensity Shuttle works for Send but not Receive

### ISSUE THREAD

**Issue by jaymis** [keijiro/Klinker#5] opened 2019-04-22 03:58 UTC
I've been testing Klinker using the Test project and a couple of Blackmagic Intensity cards I have:

Blackmagic Intensity Pro (PCIe) and Intensity Shuttle (USB3)

Both devices show up as their correct names in the "Device" selection box of both Frame Sender and Frame Receiver.

Intensity Shuttle works using Frame Sender - I can change Format to send different frame rates, and the teapot shows up on my Blackmagic Video Assist with the correct frame rate information.

Frame Receiver doesn't seem to work for either device though. 

On the Intensity Shuttle when I start the project, my camera feed shows up from the HDMI Out, which tells me the USB device has started up and is at least seeing frames from the camera.

However the "Format" box shows "525i59.94 NTSC", which is incorrect (camera is sending 1080p25). I'm guessing this might be the first format available so it defaults to that?

I've tried disabling the Frame Sender object, and tried setting the camera to a different frame rate (1080p30). 

I've also tried using both Blackmagic Desktop Video 10 and 11. I was originally on 11, but saw on another issue that the library doesn't support the 11 API, so I tried rolling back to 10. Same result.

Any thoughts? It would be amazing if I could get this work for Intensity devices. I've been using the AVPro Video and AVPro Decklink unity plugins, but they're expensive and unreliable.

/Edit: Forgot to mention my Unity version! Running 2018.3.12f1

**Comment by keijiro** [comment] 2019-04-22 05:21
First of all, please understand that this is a nearly abandoned project. I stopped working on it because I realized that the DeckLink devices don't suffice my requirement (strict synchronization with genlock on an app side).

Actually I can't remember how it works, but I think you have to use the Desktop Video configuration tool to set the input video format with Shuttle devices. DeckLink devices don't need it because it has auto format detection functionality.

**Comment by jaymis** [comment] 2019-04-22 10:30
The Desktop Video configuration tool situation is a bit weird, but yes, I've set the input video format with it. Doesn't seem to help :) 

They're slightly strange and unpredictable devices. Most video capture cards seem to be weird in some way, so I'm not really surprised that I'm having issues.

Thanks for sharing the library anyway! I'm going to need SDI capture soon, so I've purchased a Decklink Mini Recorder 4K to test.

**Comment by jaymis** [comment] 2019-04-29 04:27
Decklink Mini Recorder 4K arrived today, and it worked perfectly. 

So perhaps this thread may be helpful for other Blackmagic capture device users in the future: 

Even though the Blackmagic Intensity products (I've tested Intensity Pro PCI and Intensity Shuttle USB3) use the same Desktop Video software/API as the Decklink devices, they don't necessarily work the same way.

**Comment by claudia78** [comment] 2019-12-19 03:24
Even I am also undergoing with the relevant situation.I am also undergoing with the ample number of issues regarding the blackmagic. I am not getting at all any image when I am adding the  Intensity Shuttle as a shot in Wirecast 8.3, in Black Magic Media Express. If also I am  getting an image but in Wirecast I do not get any possible settings since all the fields are blank.I am facing problem for the Arlo too.I have followed out the manuals as required for [arlo home security review](https://netgears.support/arlo-security-camera/
).

**Comment by keijiro** [comment] 2020-11-28 08:03
I'm closing this issue now as it doesn't reproduce on my side. Please feel free to reopen it if it still reproduces.

**Closed as completed by keijiro** 2020-11-28 08:03 UTC
Labels: question
